# Generated by Django 2.0.1 on 2018-02-08 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rsvp', '0006_auto_20180208_0114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='date',
        ),
    ]
