# Generated by Django 2.0.1 on 2018-02-08 15:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rsvp', '0007_remove_event_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='invite',
            field=models.ManyToManyField(related_name='invite', to=settings.AUTH_USER_MODEL),
        ),
    ]
