# Generated by Django 2.0.1 on 2018-02-09 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsvp', '0010_choice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='event',
            new_name='event_belong',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='question_name',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='choice',
            name='choice_text',
            field=models.CharField(default='', max_length=200),
        ),
    ]
