# Generated by Django 2.0.1 on 2018-02-12 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rsvp', '0013_auto_20180211_1816'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='gest',
            new_name='guest',
        ),
    ]
